### PR TITLE
Return centroids, uses a property object for params and store data calculated at each iteration

### PR DESCRIPTION
**Pull request by automata**
The main method returns an object instead of an array. This object has the clusters' ids and the centroids calculated for each cluster. It also has an optional "history" of all the cluster's ids and centroids calculated for each iteration. Such information is really helpful when someone needs to plot each step of the algorithm. Calculated centroid for each cluster is commonly used when someone wants a representative point for a cluster.

By using the property object (`props`), someone can easily set parameters like the new `withIter`: if `true`, data calculated during iterations are stored.

I updated the documents (pls, see README) and tests to reflect such changes.

### CODE REVIEW

**Comment by maasencioh** [comment]
Hello, thanks for the help, we're developing new features here also, so if you have another idea to improve thinks I'll be glad to hear about it, obrigado por tudo.

**Comment by targos** [comment]
Thank you @automata . I just released [v0.1.0](https://www.npmjs.com/package/ml-kmeans) with your additions.

Note that we are working on a generic way to give access to intermediate results with iterative algorithms like kmeans and self-organising maps.
It will be implemented following the [ES2015 iterator interface]() (allowing to write code similar to `for (let iter of kmeans.compute()){ /* process current result */ }`).

**Comment by automata** [comment]
Thank you for accepting that and releasing 0.1.0.

Using an iterator interface seems like the right way to go. I'm curious to know more about it and to contribute as much as possible.

**Comment by targos** [comment]
Sorry I just realized my link to the ES2015 spec was wrong. Here it is: http://www.ecma-international.org/ecma-262/6.0/#sec-iteration

**Pull request merged**
